# Generated by Django 4.2.1 on 2023-05-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maize', '0008_myimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myimage',
            old_name='image',
            new_name='corn_Image',
        ),
    ]
